config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'
  get '/uber' => 'home#uber'
  get '/kontakt' => 'home#kontakt'
  resources :blogs
  resources :pets
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
 has_one_attached :image
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :description, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
# zeigt die haupt seite 
# das view ist unter view/blog/index zu finden 
def index
   @blogs = Blog.all
 end
 # zeigt die uber uns  seite 
# das view ist unter view/blog/uber zu finden 
 def uber
 end
 # zeigt die kontakt seite 
# das view ist unter view/blog/kontaakt zu finden 
 def kontakt
 end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title   %>
    <%= form.text_field :title, :class => 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, :class => 'form-control' %>
  </div>

<div class="field form-group">
    <%= form.label :image %>
    <%= form.file_field :image, :class => 'form-control' %>
  </div>
  <div class="actions form-group">
    <%= form.submit :'Blog hinzufuegen' , :class => 'btn btn-submit' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Blog erstellen ', new_blog_path %>

<h1>List alle Blogs die  verfuegabr sind</h1>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Bild</th>
      <th colspan="3">Aktion</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.description %></td>
        <td>			<%= image_tag(blog.image, :class => "img-fluid rounded", style: 'height:100px;width:100px;') %></td>
        <td><%= link_to 'Anzeigen', blog %></td>
        <td><%= link_to 'Bearbeiten', edit_blog_path(blog) %></td>
        <td><%= link_to 'Loschen', blog, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/blogs/new.html.erb
<h1>Neue Blog</h1>
<%= link_to 'Back', blogs_path %>

<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@blog.image) %>
</p>


</div>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
	<div class="banner">
		<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
			</ol>
			<div class="carousel-inner" role="listbox">
				<div class="carousel-item active">
					<div class="carousel-caption">
						<h3>Gold Jewellery </h3>
						<h5>2018
							<span>New Looks</span>
						</h5>
					</div>
				</div>
				<div class="carousel-item item2">
					<div class="carousel-caption">
						<h3>MrsThi </h3>
					
					</div>
				</div>
				<div class="carousel-item item3">
					<div class="carousel-caption">
						<h3>Pinara </h3>
						<h5>
							<span></span>
						</h5>
					</div>
				</div>
				<div class="carousel-item item4">
					<div class="carousel-caption">
						<h3>Flexi Rings </h3>
						<h5>2018
							<span>New Looks</span>
						</h5>
					</div>
				</div>
			</div>
			<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		</div>
	</div>


<section class="banner-bottom-w3ls-agileinfo">
		<!-- Portfolio -->
		<div class="portfolio" id="portfolio">
			<div class="container">
				<h3 class="tittle text-center">Latest Collection</h3>
				<div class="inner-sec-wthree-agileits">

					<ul class="portfolio-categ filter text-center mb-lg-5 mb-3">
						<li class="port-filter all active">
							<a href="#">All</a>
						</li>
						
					</ul>


					<ul class="portfolio-area clearfix">

     <% @blogs.each do |blog| %>
     <li class="portfolio-item2" data-id="id-1" data-type="cat-item-2">
							<div>
								<span class="image-block">
<a class="image-zoom" href='<%= url_for(blog.image)  %>' data-gal="prettyPhoto[gallery]">

	
										<%= image_tag(blog.image, :class => "img-fluid rounded", style: 'height:250px;width:250px;') %>
			
									</a>
                     <p><%= blog.description %></p>
								</span>
							</div>
						</li>
    <% end %>

						
							
								
									
							
						
						
					</ul>
			
					<!--end portfolio-area -->
				</div>
			</div>
		</div>
	</section>
   
 
  

<br>

app/views/home/kontakt.html.erb
<section class="banner-bottom-w3ls-agileinfo">
			<div class="container">
					<h3 class="tittle text-center">Hier konnt ihr uns nen Emails schicken</h3>
		<div class="row inner-sec-wthree-agileits">
			<div class="col-md-8 mail_form">
					<form action="#" method="post">
							<span class="input input--chisato">
							<input class="input__field input__field--chisato" name="Name" type="text" id="input-13" placeholder=" " required="" />
							<label class="input__label input__label--chisato" for="input-13">
								<span class="input__label-content input__label-content--chisato" data-content="Name">Name</span>
							</label>
							</span>
							<span class="input input--chisato">
							<input class="input__field input__field--chisato" name="Email" type="email" id="input-14" placeholder=" " required="" />
							<label class="input__label input__label--chisato" for="input-14">
								<span class="input__label-content input__label-content--chisato" data-content="Email">Email</span>
							</label>
							</span>
							<span class="input input--chisato">
							<input class="input__field input__field--chisato" name="Subject" type="text" id="input-15" placeholder=" " required="" />
							<label class="input__label input__label--chisato" for="input-15">
								<span class="input__label-content input__label-content--chisato" data-content="Subject">Subject</span>
							</label>
							</span>
							<textarea name="Message" placeholder="Your comment here..." required=""></textarea>
							<input type="submit" value="Submit">
						</form>
				
			</div>
			
			
		</div>

	

	</div>
	</section>

app/views/home/uber.html.erb
<section class="banner-bottom-w3ls-agileinfo">
		<div class="container">
			<h3 class="tittle text-center">About Us</h3>
			<div class="row inner-sec-wthree-agileits">
				<div class="col-lg-7 bt-bottom-info ab">
					<img src="images/banner1.jpg" class="img-fluid" alt=" ">

				</div>
				<div class="col-lg-5 bt-bottom-info">
					<h5>Wer sind Wir</h5>
					<p class="ab-para">
Wir sind 2 studenten aus der HWR
 </p>
				</div>

			</div>


			
			<!-- /.row -->
			
		</div>
	</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Our blog</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="//fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Prata" rel="stylesheet">

	
	
<%= stylesheet_link_tag "bootstrap" %>
<%= stylesheet_link_tag "style" %>
<%= stylesheet_link_tag "prettyPhoto" %>
<%= stylesheet_link_tag "owl.carousel" %>
<%= stylesheet_link_tag "owl.theme" %>
<%= stylesheet_link_tag "fontawesome-all" %>
<%= stylesheet_link_tag "prettyPhoto" %>
<%= stylesheet_link_tag "prettyPhoto" %>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header>


<%= javascript_include_tag('scmplayer.js') %>
		<div class="top-bar_sub_w3layouts_agile">
			<h6>
				
			</h6>
			<div class="log">
				
				<h5>

<%= link_to "Admin Bereich", { :controller => :blogs, :action => :index }, { class: "sign" } %>


						
				</h5>
			</div>
			<div class="clearfix"> </div>
		</div>

		<div class="header_top" id="home">
			<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
				    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<a class="navbar-brand" href="/">
					<i class="far fa-gem"></i>HWR berlin</a>
				<div class="collapse navbar-collapse" id="navbarNavDropdown">
					<ul class="navbar-nav">
						<li class="nav-item active">
							<a class="nav-link cool" href="/">Home
								<span class="sr-only">(current)</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link cool" href="uber">uber uns</a>
						</li>
						<li class="nav-item">
							<a class="nav-link cool" href="kontakt">Kontakt</a>
						</li>
						
						
					</ul>

				</div>
				<div class="header-search-agileits-w3ls">
					
				</div>
			</nav>

		</div>
	</header>

<div class='container'>
    <%= yield %>
</div>



			<footer>

		<div class="instagram-posts">
			<h3 class="tittle cen foot">Istagram Posts</h3>
			<div class="row footer-top">
				<!-- instagram posts -->
				<div class="col-md-2 col-sm-2 footer-grid-img">
					<a href="single.html">
						<img src="images/g6.jpg" class="img-fluid" alt="" />
					</a>
				</div>
				<div class="col-md-2 col-sm-2 footer-grid-img">
					<a href="single.html">
						<img src="images/g2.jpg" class="img-fluid" alt="" />
					</a>
				</div>
				<div class="col-md-2 col-sm-2 footer-grid-img">
					<a href="single.html">
						<img src="images/g4.jpg" class="img-fluid" alt="" />
					</a>
				</div>
				<div class="col-md-2 col-sm-2 footer-grid-img">
					<a href="single.html">
						<img src="images/g6.jpg" class="img-fluid" alt="" />
					</a>
				</div>
				<div class="col-md-2 col-sm-2 footer-grid-img">
					<a href="single.html">
						<img src="images/g8.jpg" class="img-fluid" alt="" />
					</a>
				</div>
				<div class="col-md-2 col-sm-2 footer-grid-img">
					<a href="single.html">
						<img src="images/g1.jpg" class="img-fluid" alt="" />
					</a>
				</div>
			</div>
			<!-- //instagram posts -->
			<!-- subscribe -->
			<div class="footer-bottom-w3layouts-agileinfo">
				<div class="subscribe-main text-center">
					<h2>Signup to our newsletter</h2>
					<div class="subscribe-form">
						<form action="#" method="post" class="subscribe_form">
							<input class="form-control" type="email" placeholder="Enter your email..." required="">
							<input class="form-control" type="submit" value="Subscribe">
						</form>

					</div>
					<p>We respect your privacy.No spam ever!</p>
				</div>
				<!-- //subscribe -->
				<!-- footer -->
				<div class="footer-cpy text-center">
					<div class="footer-social">
						<div class="copyrighttop">
							<ul>
								<li>
									<a class="facebook" href="#">
										<i class="fab fa-facebook-f"></i>
										<span>Facebook</span>
									</a>
								</li>
								<li>
									<a class="facebook" href="#">
										<i class="fab fa-twitter"></i>
										<span>Twitter</span>
									</a>
								</li>
								<li>
									<a class="facebook" href="#">
										<i class="fab fa-google-plus-g"></i>
										<span>Google+</span>
									</a>
								</li>
								<li>
									<a class="facebook" href="#">
										<i class="fab fa-pinterest-p"></i>
										<span>Pinterest</span>
									</a>
								</li>
							</ul>

						</div>
					</div>
					
				</div>

				<!-- //footer -->
			</div>
		</div>
	</footer>
<script>
		
	</script>
	<!-- start-smoth-scrolling -->

	<script>
		
	</script>


<%= javascript_include_tag('jquery-2.2.3.min.js') %>
<%= javascript_include_tag('bootstrap.js') %>

	


<%= javascript_include_tag('owl.carousel.js') %>
	


<%= javascript_include_tag('move-top.js') %>
<%= javascript_include_tag('easing.js') %>
<%= javascript_include_tag('jquery-1.7.2.js') %>
<%= javascript_include_tag('jquery.quicksand.js') %>
<%= javascript_include_tag('script.js') %>
<%= javascript_include_tag('jquery.prettyPhoto.js') %>

  </body>
</html>